name: Deploy .NET CDK + Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install AWS CDK CLI
        run: npm install -g aws-cdk

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Restore dependencies
        run: |
          dotnet restore OpenAILambda/src/OpenAILambda/OpenAILambda.csproj
          dotnet restore Infra/Infra.csproj

      - name: Publish Lambda
        run: |
          dotnet publish OpenAILambda/src/OpenAILambda/OpenAILambda.csproj \
            -c Release \
            -o ./OpenAILambda/bin/Release/net6.0/publish \
            /p:PublishReadyToRun=false

      - name: Verify Lambda output directory
        run: |
          ls -la ./OpenAILambda/bin/Release/net6.0/publish
          echo "Lambda output directory verified"

      - name: Build CDK app
        working-directory: Infra
        run: dotnet build --configuration Release

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: CDK Bootstrap
        working-directory: Infra
        run: |
          ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          cdk bootstrap aws://$ACCOUNT_ID/$AWS_REGION --require-approval never

      - name: CDK Synth
        working-directory: Infra
        run: |
          cdk synth --app "dotnet run -c Release --no-build"

      - name: CDK Deploy
        working-directory: Infra
        run: |
          cdk deploy InfraStack --app "dotnet run -c Release --no-build" --require-approval never